name: CI

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
    build:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup

            - run: pnpm run lint
